### Load in NumPy (remember to pip install numpy first)

In [52]:
import numpy as np

### The Basics

In [53]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [103]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b.dtype)

float64


In [55]:
# Get Dimension
a.ndim

1

In [56]:
# Get Shape
b.shape

(2, 3)

In [57]:
# Get Type
a.dtype

dtype('int32')

In [58]:
# Get Size
a.itemsize

4

In [59]:
# Get total size
a.nbytes

12

In [60]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [61]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [62]:
# Get a specific element [r, c]
a[1, 5]

13

In [63]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [65]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [66]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [118]:
b = np.array([[1,2],[3,4],[5,6],[7,8]])
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [121]:
# Get specific element (work outside in)
b[:,1]

array([2, 4, 6, 8])

In [123]:
# replace 
b[1,:] = [9,9]

In [124]:
b

array([[1, 2],
       [9, 9],
       [5, 6],
       [7, 8]])

### Initializing Different Types of Arrays

In [71]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [73]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [74]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [75]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.94509451, 0.27290717],
       [0.80918151, 0.44185681],
       [0.88105138, 0.89181898],
       [0.46951658, 0.02645858]])

In [76]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 2,  3,  7],
       [-4,  5, -3],
       [-4, -2, -2]])

In [77]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [79]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [125]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
b

[1 2 3]


array([100,   2,   3])

### Mathematics

In [135]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [136]:
a + 2

array([3, 4, 5, 6])

In [137]:
a - 2

array([-1,  0,  1,  2])

In [138]:
a * 2

array([2, 4, 6, 8])

In [139]:
a / 2
a

array([1, 2, 3, 4])

In [140]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [141]:
a ** 2

array([ 1,  4,  9, 16])

In [142]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [143]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [144]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [145]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [92]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [93]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.min(stats)

1

In [95]:
np.max(stats, axis=1)

array([3, 6])

In [96]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [146]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [98]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [100]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [101]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])